name: Run Trading Bot

on:
  schedule:
    # Every 15 minutes on weekdays
    - cron: '*/15 * * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train models
        run: python train_model.py

      - name: Run trading bot
        run: python bot.py
jobs:
  test-connectivity:
    runs-on: ubuntu-latest
    steps:
      - name: Test HTTPS connection to OpenAI API
        run: |
          curl -v https://api.openai.com/v1/models || echo "Connection failed"
