name: Trading Bot

on:
  schedule:
    # Runs every 15 minutes on weekdays (Mon-Fri) UTC time
    - cron: "*/15 * * * 1-5"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Trading Bot
        env:
          ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          TRADINGECONOMICS_KEY: ${{ secrets.TRADINGECONOMICS_KEY }}
        run: |
          python bot.py
