name: Run Financial Data Fetcher

on:
  push:
    branches: [main]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies here, for example:
          # pip install requests

      - name: Run data fetcher script
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          TRADINGECONOMICS_KEY: ${{ secrets.TRADINGECONOMICS_KEY }}
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          python data_fetcher.py
